module tb;
integer i,j;
reg[7:0]ch;
  initial begin
    ch="A";
    for(i=1;i<=26;i=i+1)begin
      for(j=1;j<=i;j=j+1)begin
        $write("%c",ch);
      end
       $write("\n");
       ch=ch+1;
    end
  end
endmodule

/*
OUTPUT

# A
# BB
# CCC
# DDDD
# EEEEE
# FFFFFF
# GGGGGGG
# HHHHHHHH
# IIIIIIIII
# JJJJJJJJJJ
# KKKKKKKKKKK
# LLLLLLLLLLLL
# MMMMMMMMMMMMM
# NNNNNNNNNNNNNN
# OOOOOOOOOOOOOOO
# PPPPPPPPPPPPPPPP
# QQQQQQQQQQQQQQQQQ
# RRRRRRRRRRRRRRRRRR
# SSSSSSSSSSSSSSSSSSS
# TTTTTTTTTTTTTTTTTTTT
# UUUUUUUUUUUUUUUUUUUUU
# VVVVVVVVVVVVVVVVVVVVVV
# WWWWWWWWWWWWWWWWWWWWWWW
# XXXXXXXXXXXXXXXXXXXXXXXX
# YYYYYYYYYYYYYYYYYYYYYYYYY
# ZZZZZZZZZZZZZZZZZZZZZZZZZZ

*/
